management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://47.97.90.221:7001/eureka/,http://47.97.90.221:7002/eureka/,http://47.97.90.221:7003/eureka/

server:
  port: 8765

spring:
  application:
    name: ZUUL
  cloud:
    loadbalancer:
      retry:
        enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

# ribbon.ConnectTimeout+ribbon.ReadTimeout<hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds
ribbon:
  ConnectTimeout: 2500
  ReadTimeout: 5000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 0

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: HYDRA
      retryable: true
  retryable: true
